version: '3'

services:
  redis:
    image: redis:6
  server:
    build: ../2.3/server
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
    restart: unless-stopped

  client:
    build: ../2.3/client
    ports:
      - 5000:5000
