version: '3'

services:
  training:
    build: ./ml-kurkkumopo-training-master
    volumes:
      - mldata:/src/model
      - imgs:/src/imgs

  server:
    build: ./ml-kurkkumopo-backend-master
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - mldata:/src/model


  client:
    build: ./ml-kurkkumopo-frontend-master
    ports:
      - 3000:3000

volumes:
  mldata:
  imgs: