# Image based on Debian
FROM openjdk:8

WORKDIR /myapp
# Copy the sources into the container
COPY ./spring-example-project-master /myapp
# App is build in the same container that is going to be deployed
RUN ./mvnw package
EXPOSE 8080
# Command ran as root
CMD java -jar ./target/docker-example-1.1.3.jar
